import './style.css';
type Source = { id: string; name: string; description?: string; transport: 'stdio' | 'http'; command?: string; args?: string[]; env?: Record<string, string>; url?: string; status: 'running' | 'stopped'; toolCount: number; error?: string };
type State = { sources: Source[]; uplink: { url: string; enabled: boolean; configured: boolean; status: string; host: string }; activity: Array<{ time: string; label: string; detail: string }>; endpoint: string; tools: number };
const root = document.querySelector<HTMLDivElement>('#app')!;
let state: State;
let editing: Source | undefined;
const escape = (value: unknown) => String(value ?? '').replace(/[&<>"']/g, character => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' })[character]!);
const request = async (path: string, method = 'GET', data?: unknown) => { const response = await fetch(`/api/${path}`, { method, headers: data ? { 'content-type': 'application/json' } : undefined, body: data ? JSON.stringify(data) : undefined }); const result = await response.json(); if (!response.ok) throw new Error(result.error ?? 'Request failed'); return result; };
const page = () => location.pathname === '/remote' ? 'remote' : location.pathname === '/add' ? 'add' : 'mcps';
const note = (message: string, error = false) => { const element = document.querySelector<HTMLElement>('#notice'); if (element) { element.textContent = message; element.className = `notice ${error ? 'error' : ''}`; setTimeout(() => { element.textContent = ''; }, 4000); } };
async function refresh() { state = await request('state'); render(); }
function shell(content: string, title: string) {
  const active = page();
  root.innerHTML = `<div class="shell"><aside class="sidebar"><a class="brand" href="/mcps"><span class="brand-icon">✳</span><span>MCP <small>UPLINK</small></span></a><div class="side-label">WORKSPACE</div><nav><a class="${active === 'mcps' || active === 'add' ? 'active' : ''}" href="/mcps"><span>▦</span> MCPs</a><a class="${active === 'remote' ? 'active' : ''}" href="/remote"><span>⇄</span> Remote</a></nav><div class="sidebar-bottom"><div class="side-label">LOCAL ENDPOINT</div><div class="side-endpoint">127.0.0.1:${new URL(state.endpoint).port}/mcp</div><div class="daemon"><span class="live-dot"></span><div><strong>Uplink daemon</strong><small>Running locally</small></div></div></div></aside><div class="workspace"><header class="topbar"><span>MCP Uplink <span class="slash">/</span> <strong>${title}</strong></span><span class="top-status"><span class="live-dot"></span> Local daemon online</span></header><main>${content}</main></div></div><div id="notice" class="notice"></div>`;
}
function renderMcps() {
  const rows = state.sources.map(source => `<div class="source-row"><div class="source-name"><span class="source-icon">${source.transport === 'stdio' ? '⌘' : '◎'}</span><div><strong>${escape(source.name)}</strong><small>${escape(source.description || (source.transport === 'stdio' ? 'Local process' : 'HTTP connection'))}</small></div></div><span class="pill ${source.transport}">${source.transport.toUpperCase()}</span><span class="status ${source.status}"><span class="live-dot"></span>${source.status === 'running' ? 'Running' : 'Stopped'}</span><strong class="count">${source.toolCount}</strong><code class="source-location">${escape(source.transport === 'stdio' ? [source.command, ...(source.args ?? [])].join(' ') : source.url)}</code><div class="row-actions"><button data-action="${source.status === 'running' ? 'stop' : 'start'}" data-id="${source.id}" class="small-button">${source.status === 'running' ? 'Stop' : 'Start'}</button><button data-action="restart" data-id="${source.id}" class="icon-button" title="Restart">↻</button><button data-action="edit" data-id="${source.id}" class="icon-button" title="Edit">✎</button><button data-action="remove" data-id="${source.id}" class="icon-button" title="Remove">×</button></div>${source.error ? `<small class="source-error">${escape(source.error)}</small>` : ''}</div>`).join('');
  shell(`<div class="page-heading"><div><div class="eyebrow">LOCAL CONTROL</div><h1>Local MCPs</h1><p>Run local MCP servers. Reach every available tool through one endpoint.</p></div><a class="primary-button" href="/add">＋ Add MCP</a></div><section class="endpoint-panel"><div class="eyebrow bright">LOCAL AGGREGATE MCP</div><div class="endpoint-top"><div><h2>One endpoint. All your local tools.</h2><p>Connect a local MCP client to this address.</p></div><span class="online-tag"><span class="live-dot"></span> Online</span></div><div class="endpoint-copy"><code>${escape(state.endpoint)}</code><button id="copy">Copy endpoint</button></div><div class="endpoint-meta"><span><strong>${state.sources.length}</strong> configured MCPs</span><span><strong>${state.tools}</strong> tools exposed</span><span>⌁ Loopback only · No authentication</span></div></section><section class="card"><div class="card-head"><div><h2>Configured MCPs</h2><p>Start, stop, and manage local connections.</p></div><span class="counter">${state.sources.length} total</span></div><div class="table-head"><span>MCP</span><span>TRANSPORT</span><span>STATUS</span><span>TOOLS</span><span>PROCESS / ENDPOINT</span><span>ACTIONS</span></div>${rows || `<div class="empty">No MCPs configured yet. <a href="/add">Add your first MCP</a>.</div>`}</section><section class="info-panel"><span class="info-icon">i</span><div><strong>How MCP Uplink works</strong><p>STDIO MCPs run as child processes. HTTP MCPs connect directly. All available tools appear at the local endpoint and can be advertised to your remote server.</p></div></section>`, 'MCPs');
  document.querySelector('#copy')?.addEventListener('click', () => { void navigator.clipboard.writeText(state.endpoint).then(() => note('Endpoint copied')); });
  document.querySelectorAll<HTMLButtonElement>('[data-action]').forEach(button => button.addEventListener('click', () => { void act(button.dataset.action!, button.dataset.id!); }));
}
async function act(action: string, id: string) {
  if (action === 'edit') { editing = state.sources.find(source => source.id === id); history.pushState(null, '', '/add'); render(); return; }
  if (action === 'remove' && !confirm('Remove this MCP configuration?')) return;
  try { await request(`sources/${id}${['start', 'stop', 'restart'].includes(action) ? '/' + action : ''}`, action === 'remove' ? 'DELETE' : 'POST'); await refresh(); note(`MCP ${action} complete`); } catch (error) { await refresh(); note((error as Error).message, true); }
}
function renderRemote() {
  const connected = state.uplink.status === 'connected';
  shell(`<div class="page-heading"><div><div class="eyebrow">UPLINK</div><h1>Remote uplink</h1><p>Connect MCP Uplink to a remote server so it can invoke local tools.</p></div><span class="status-badge ${connected ? 'connected' : ''}"><span class="live-dot"></span>${connected ? 'Connected' : 'Disconnected'}</span></div><div class="remote-grid"><section class="card remote-config"><div class="card-head"><div><h2>Remote server</h2><p>Use Myriad Cloud or any compatible WebSocket uplink.</p></div></div><form id="uplink-form" class="form"><label>WebSocket URL<input name="url" type="url" required value="${escape(state.uplink.url)}" placeholder="wss://api-mcp.myriadcode.com/adapter"></label><label>Credential / token<input name="token" type="password" autocomplete="off" placeholder="${state.uplink.configured ? 'Saved credential (leave blank to keep)' : 'Enter credential'}"></label><p class="hint">Stored locally. Never shown again or written to uplink logs.</p><div class="form-footer"><button class="primary-button" type="submit">${state.uplink.enabled ? 'Reconnect' : 'Connect'}</button>${state.uplink.enabled ? '<button id="disconnect" class="secondary-button" type="button">Disconnect</button>' : ''}</div></form></section><div class="remote-side"><section class="card status-card"><div class="eyebrow">CONNECTION STATUS</div><h2>${connected ? 'Connected' : 'Disconnected'}</h2><p>${escape(state.uplink.host || 'No remote server')}</p><div class="status-line"><span class="live-dot"></span>${state.uplink.enabled ? 'Uplink enabled' : 'Uplink disabled'}</div></section><section class="card capabilities"><div class="eyebrow">ADVERTISED CAPABILITIES</div><div class="metrics"><div><strong>${state.sources.length}</strong><span>Configured MCPs</span></div><div><strong>${state.tools}</strong><span>Available tools</span></div><div><strong>${state.sources.filter(source => source.status === 'running').length}</strong><span>Running MCPs</span></div></div><p>Current tool definitions are sent to remote server. Access policy stays remote.</p></section></div></div><section class="card activity"><div class="card-head"><div><h2>Uplink activity</h2><p>Recent connection and tool events.</p></div></div>${state.activity.length ? state.activity.slice(0, 8).map(item => `<div class="event"><span class="event-dot"></span><strong>${escape(item.label)}</strong><span>${escape(item.detail)}</span><time>${new Date(item.time).toLocaleTimeString()}</time></div>`).join('') : '<div class="empty">No activity yet.</div>'}</section><section class="scope-banner"><strong>Local transport. Remote policy.</strong><span>MCP Uplink manages connections and processes. Permissions, filtering, and quotas belong to remote server.</span></section>`, 'Remote');
  document.querySelector<HTMLFormElement>('#uplink-form')?.addEventListener('submit', event => { event.preventDefault(); void saveUplink(true); });
  document.querySelector('#disconnect')?.addEventListener('click', () => { void saveUplink(false); });
}
async function saveUplink(enabled: boolean) {
  const form = document.querySelector<HTMLFormElement>('#uplink-form')!;
  const data = new FormData(form);
  try { await request('uplink', 'PUT', { url: data.get('url'), token: data.get('token'), enabled }); await refresh(); note(enabled ? 'Uplink configured' : 'Uplink disconnected'); } catch (error) { note((error as Error).message, true); }
}
function renderAdd() {
  const source = editing;
  shell(`<div class="page-heading"><div><a class="back" href="/mcps">← Back to MCPs</a><div class="eyebrow">LOCAL CONFIGURATION</div><h1>${source ? 'Edit MCP' : 'Add MCP'}</h1><p>Configure a local MCP source. Its tools become available through the aggregate endpoint.</p></div></div><div class="add-layout"><section class="card add-card"><div class="card-head"><div><h2>MCP configuration</h2><p>Choose how MCP Uplink connects to this server.</p></div></div><form id="source-form" class="form"><label>Name<input name="name" maxlength="100" required value="${escape(source?.name)}" placeholder="e.g. Webpage MCP"></label><label>Description <span class="optional">optional</span><input name="description" value="${escape(source?.description)}" placeholder="What this MCP provides"></label><div class="field-label">Transport</div><div class="transport-options"><label class="transport-option"><input type="radio" name="transport" value="stdio" ${!source || source.transport === 'stdio' ? 'checked' : ''}><span><strong>⌘ &nbsp; STDIO</strong><small>Run a local process</small></span></label><label class="transport-option"><input type="radio" name="transport" value="http" ${source?.transport === 'http' ? 'checked' : ''}><span><strong>◎ &nbsp; HTTP</strong><small>Connect to an endpoint</small></span></label></div><div id="stdio-fields"><label>Command<input name="command" value="${escape(source?.command)}" placeholder="npx"></label><label>Arguments <span class="optional">one per line</span><textarea name="args" rows="3" placeholder="-y&#10;webpage-mcp">${escape(source?.args?.join('\n'))}</textarea></label><label>Environment variables <span class="optional">KEY=value, one per line; blank value keeps saved value</span><textarea name="env" rows="3" placeholder="API_TOKEN=...">${escape(Object.entries(source?.env ?? {}).map(([key, value]) => `${key}=${value}`).join('\n'))}</textarea></label></div><div id="http-fields"><label>MCP endpoint URL<input name="url" type="url" value="${escape(source?.url)}" placeholder="http://127.0.0.1:9001/mcp"></label></div><div class="form-footer"><a class="secondary-button" href="/mcps">Cancel</a><button class="primary-button" type="submit">${source ? 'Save changes' : 'Add MCP'}</button></div></form></section><aside class="guide-card"><div class="guide-icon">⌁</div><h2>One bridge for your tools</h2><p>STDIO servers are started and managed here. HTTP servers are connected directly.</p><div class="guide-rule"></div><p>Discovered tools are exposed locally at <code>${escape(state.endpoint)}</code>.</p><p>MCP Uplink does not apply local tool policy.</p></aside></div>`, source ? 'Edit MCP' : 'Add MCP');
  const toggle = () => { const stdio = document.querySelector<HTMLInputElement>('input[name=transport]:checked')?.value === 'stdio'; (document.querySelector('#stdio-fields') as HTMLElement).hidden = !stdio; (document.querySelector('#http-fields') as HTMLElement).hidden = stdio; };
  document.querySelectorAll('input[name=transport]').forEach(input => input.addEventListener('change', toggle)); toggle();
  document.querySelector<HTMLFormElement>('#source-form')?.addEventListener('submit', event => { event.preventDefault(); void saveSource(); });
}
async function saveSource() {
  const data = new FormData(document.querySelector<HTMLFormElement>('#source-form')!);
  const transport = data.get('transport');
  const common = { name: data.get('name'), description: data.get('description'), transport };
  try {
  const envEntries = String(data.get('env') ?? '').split('\n').filter(Boolean).map(line => { const at = line.indexOf('='); if (at < 1) throw new Error('Environment variable must use KEY=value'); return [line.slice(0, at).trim(), line.slice(at + 1)]; });
  const env = Object.fromEntries(envEntries);
  const input = transport === 'stdio' ? { ...common, command: data.get('command'), args: String(data.get('args') ?? '').split('\n').map(item => item.trim()).filter(Boolean), env } : { ...common, url: data.get('url') };
  await request(editing ? `sources/${editing.id}` : 'sources', editing ? 'PUT' : 'POST', input); editing = undefined; history.pushState(null, '', '/mcps'); await refresh(); note('MCP saved'); } catch (error) { note((error as Error).message, true); }
}
function render() { if (page() === 'remote') renderRemote(); else if (page() === 'add') renderAdd(); else renderMcps(); }
window.addEventListener('popstate', () => { editing = undefined; render(); });
const formActive = () => { const element = document.activeElement; return !!element && (element.tagName === 'INPUT' || element.tagName === 'TEXTAREA') && !!element.closest('#uplink-form, #source-form'); };
void refresh(); setInterval(() => { if (page() !== 'add' && !formActive()) void refresh(); }, 5000);
